Sprint 15: Core Data
AndreiChenchik/practicum-ios-TrackerApp pull request #3
Opened 2023-02-04 07:54 UTC by AndreiChenchik

2023-02-26 20:46 UTC, mmbabaev commented on TrackerApp/Components/CellView.swift
> +struct CellView_Previews: PreviewProvider {
круто!

2023-02-26 21:09 UTC, mmbabaev requested changes

2023-02-26 21:09 UTC, mmbabaev commented on TrackerApp/Scenes/NewTracker/Components/CategoryTableViewCell.swift
> +        configure(label: nil, outCorner: [], hasDivider: false)
Стоит добавить вызов super 

https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse

If you override this method, you must be sure to invoke the superclass implementation.

2023-02-26 21:09 UTC, mmbabaev commented on TrackerApp/Scenes/NewTracker/Steps/TrackerConfigViewController.swift
> +            return
можно добавить assertionFailure

2023-02-26 21:09 UTC, mmbabaev commented on TrackerApp/Scenes/NewTracker/TrackerConfig.swift
> +                return nil
это мелочь, но лучше перечислять явно все рейсы вместо default там, где это возможно. 
Так при добавлении нового case ошибки компиляции не дадут забыть про какой-то switch

2023-02-26 21:14 UTC, mmbabaev requested changes

2023-02-26 21:14 UTC, mmbabaev commented on TrackerApp/AppDelegate.swift
> +import CoreData
здесь не должно быть импорта CoreData

2023-02-26 21:14 UTC, mmbabaev commented on TrackerApp/Services/TrackerRepository.swift
> +final class TrackerRepository: NSObject, ObservableObject {
нужно поделить на несколько репозиториев

2023-02-26 21:14 UTC, mmbabaev commented on TrackerApp/Services/TrackerRepository.swift
> +final class TrackerRepository: NSObject, ObservableObject {
также лучше соотносить названия классов с описанием в "Убедитесь что"

2023-02-27 16:18 UTC, AndreiChenchik commented on TrackerApp/Components/CellView.swift
> +struct CellView_Previews: PreviewProvider {
Спасибо! Оч помогло ускорить работу)

2023-02-27 16:21 UTC, AndreiChenchik commented on TrackerApp/Scenes/NewTracker/TrackerConfig.swift
> +                return nil
Согласен, действительно по лени проэкономил несколько символов и ухудшил. 
Исправил!

2023-02-27 16:27 UTC, AndreiChenchik commented on TrackerApp/Scenes/NewTracker/Steps/TrackerConfigViewController.swift
> +            return
Не совсем так, тап может таки дойти до коллекции, если например вьюха с именем не перехватила контроль, когда тапнули в паддинг, так что вполне может быть такой кейс.

2023-02-27 16:28 UTC, AndreiChenchik commented on TrackerApp/Scenes/NewTracker/Components/CategoryTableViewCell.swift
> +        configure(label: nil, outCorner: [], hasDivider: false)
Вот это я маханул! Исправил

2023-02-27 16:33 UTC, AndreiChenchik commented on TrackerApp/AppDelegate.swift
> +import CoreData
@mmbabaev я тут теряюсь немного, я понимаю что такие требования, но мне кажется они некорректные:
1. ведь у нас sqlite один (база)
2. поэтому контейнер должен быть один, чтобы не было параллельного доступа из нескольких контейнеров
3. Store файлы у нас равнозначны, поэтому они либо должны создавать каждый свой контейнер, либо получать его извне
4. Так как мы не хотим параллельного доступа - нужно его один создавать и передавать им
5. Если так то нужен еще один импорт CoreData где-то вне Store файлов
6. Либо объявлять в одном из Store файлов синглтон, просто чтобы обойти требование, но делать такое никакого желания нет и это хак к странному требованию

попробую написать автору

2023-02-27 16:42 UTC, mmbabaev commented on TrackerApp/AppDelegate.swift
> +import CoreData
понял, согласен, можно сделать или отдельный класс, хранящий контейнер, или оставить его в AppDelegate, считать здесь критическим замечанием не буду если что.

2023-02-27 16:56 UTC, andreichenchik commented on TrackerApp/Services/TrackerRepository.swift
> +final class TrackerRepository: NSObject, ObservableObject {
Тоже странное требование, копипаст резалт контроллера получается, но упражнение интересное, так что можно и сделать. Если получится сделаю на дженериках!

2023-02-27 17:56 UTC, AndreiChenchik commented on TrackerApp/Services/TrackerRepository.swift
> +final class TrackerRepository: NSObject, ObservableObject {
Заоверинжинирил требование!

2023-02-27 17:58 UTC, AndreiChenchik commented
Андрей, проверил твою работу, не выполнены критические требования:

- [ ] добавлены классы TrackerStore, TrackerCategoryStore, TrackerRecordStore для абстрагирования Core Data; (работа идет через один класс репозитория)
- ~нигде, кроме Store.swift-файлов, нет строчки import CoreData; иначе говоря - приложение надежно абстрагировано от Core Data. (в AppDelegate хранится persistentContainer)~
    

Некритические замечания: 
- [ ] добавить вызов `super.prepareForReuse` 
- [ ] не использовать default в switch по возможности

Понравились SwiftUI превьюшки.

Жду исправлений!

2023-02-27 18:16 UTC, mmbabaev approved these changes

2023-02-27 18:16 UTC, mmbabaev commented on TrackerApp/Services/Store.swift
> +                preconditionFailure("Something went terribly wrong")
можно и конкретнее написать здесь сообщение, тут понятно что не так :)
Также как вариант можно сделать static свойство shared в классе AppDelegate

2023-02-27 18:16 UTC, mmbabaev commented on TrackerApp/Services/Store.swift
> +    weak var delegate: StoreDelegate?
свойства вроде как можно скрыть private

2023-02-27 18:16 UTC, mmbabaev commented on TrackerApp/Services/TrackerRepository.swift
> +                trackerCD.schedule = try? JSONEncoder().encode(schedule)
лучше вынести JSONEncoder в отдельное свойство

2023-02-27 18:16 UTC, mmbabaev commented on TrackerApp/Services/TrackerRepository.swift
> +                trackerCD.schedule = try? JSONEncoder().encode(schedule)
еще может красивше покажется через map:
`trackerCD.schedule = tracker.schedule.map { try? encoder.encode($0) }`

2023-02-27 18:18 UTC, mmbabaev approved these changes

2023-02-27 18:18 UTC, mmbabaev commented on TrackerApp/Scenes/Trackers/TrackersCollectionViewCell.swift
>          configure(with: nil)
вообще кажется необязательно переопределять prepareForReuse в каждой ячейке. Если там просто меняется текст, то можно обойтись и без него

2023-02-27 19:03 UTC, AndreiChenchik commented on TrackerApp/Services/TrackerRepository.swift
> +                trackerCD.schedule = try? JSONEncoder().encode(schedule)
Декодеры/энкодеры переместил, действительно не оч хорошо их пересоздавать. А по поводу мапа - мне не array нужен, а просто кусок данных, так что нужен просто прогон всего сета через энкодер, а не поэелементам

2023-02-27 19:03 UTC, AndreiChenchik commented on TrackerApp/Scenes/Trackers/TrackersCollectionViewCell.swift
>          configure(with: nil)
Да, согласен, я скорее пытаюсь это как паттерн применять, чтобы нигде не забыть и всегда единую схему. В след раз опять подумаю как правильнее сделать :) Пока оставлю

2023-02-27 19:25 UTC, AndreiChenchik commented on TrackerApp/Services/Store.swift
> +    weak var delegate: StoreDelegate?
Спасибо, мой косяк!

2023-02-27 19:29 UTC, AndreiChenchik commented on TrackerApp/Services/Store.swift
> +                preconditionFailure("Something went terribly wrong")
Согласен, писать нужно понятнее. А методику использовал от авторов, по хорошему вообще тут DI нормальный надо поднимать, так что пока оставлю как есть.

2023-02-27 19:30 UTC, merged